# shell configuration
"sh/env" = "~/.env"
"bash/bashrc" = "~/.bashrc"
"bash/bash_profile" = "~/.bash_profile"
"zsh/zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.zshrc"

# general dotfiles
"dunst" = "~/.config/dunst"
"foot" = "~/.config/foot"
"kanshi" = "~/.config/kanshi"
"kvantum" = "~/.config/Kvantum"
"nvim" = "~/.config/nvim"
"rofi" = "~/.config/rofi"
"sway" = "~/.config/sway"
"swaylock" = "~/.config/swaylock"
"waybar" = "~/.config/waybar"

# GTK/QT application theming
"linux-theming/gtk-2.0" = "~/.config/gtk-2.0"
"linux-theming/gtk-3.0" = "~/.config/gtk-3.0"
"linux-theming/qt6ct" = "~/.config/qt6ct"
