[helpers]

[base]
"depends" = ["bash", "zsh"]

[bash.files]
"home/.bashrc" = "~/.bashrc"
"home/.bash_profile" = "~/.bash_profile"

[zsh.files]
"home/.zshenv" = "~/.zshenv"
"home/.config/zsh/.zshrc" = "~/.config/zsh/.zshrc"
