[helpers]


[base]
"depends" = ["bash", "git", "nvim", "zsh"]


[bash]
"depends" = ["sh"]

    [bash.files]
    "home/.bashrc" = "~/.bashrc"
    "home/.bash_profile" = "~/.bash_profile"


[git]

    [git.files]
    "home/.config/git/config" = "~/.config/git/config"


[nvim]

    [nvim.files]
    "home/.config/nvim/" = "~/.config/nvim/"


[sh]

    [sh.files]
    "home/.config/sh/aliases.sh" = "~/.config/sh/aliases.sh"
    "home/.config/sh/env.sh" = "~/.config/sh/env.sh"


[zsh]
"depends" = ["sh"]

    [zsh.files]
    "home/.zshenv" = "~/.zshenv"
    "home/.config/zsh/.zshrc" = "~/.config/zsh/.zshrc"
